export const DATE_FORMATS = {
  TIME: "HH:mm",
  STANDARD_DATE: "YYYY-MM-DD",
  STANDARD_DATE_TIME: "YYYY-MMDD HH:mm",
  DISPLAY_DATE: "DD/MM/YYYY",
  DISPLAY_DATETIME: "DD/MM/YYYY HH:mm",
  ISO: "YYYY-MM-DDTHH:mm:ss.ssZ",
};
